#!/usr/bin/env bash
# Pin every runtime dependency: install requirements.in in a clean Linux container with
# Python 3.10 (the oldest Python the judges allow, so every pinned version supports it),
# freeze the result and write requirements.txt. Run from anywhere on a machine with Docker.
set -euo pipefail
cd "$(dirname "$0")/.."

docker run --rm --user "$(id -u):$(id -g)" -e HOME=/tmp \
    -v "$PWD":/repo -w /repo python:3.10-slim bash -c '
set -euo pipefail
python -m venv /tmp/venv
/tmp/venv/bin/pip install --quiet --upgrade pip
/tmp/venv/bin/pip install --quiet -r requirements.in
{
    echo "# Generated by tools/pin_requirements.sh from requirements.in; do not edit by hand."
    echo "# Resolved on $(uname -m) Linux with Python $(/tmp/venv/bin/python -V | cut -d" " -f2)."
    grep -e "^--extra-index-url" requirements.in
    /tmp/venv/bin/pip freeze
} > requirements.txt
'
echo "requirements.txt updated; commit it."
